# Reload when pressing r
unbind r
bind r source-file ~/.tmux.conf

#super key
set -g prefix `

# Vim Motions
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1
set-option -g renumber-windows on

# Enable mouse
set -g mouse on

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# Ressurect
set -g @resurrect-capture-pane-contents 'on'
set -g @resurrect-save 'x'
set -g @resurrect-restore 'f'
# Continuum 
set -g @continuum-save-interval '15'
set -g @continuum-restore 'on'
# Theme
set -g @plugin 'catppuccin/tmux#v2.1.3'
set -g @thm_mauve "#87afff"
set -g @catppuccin_window_status_style 'custom'
set -g @catppuccin_status_background "none"
set -g @catppuccin_window_left_separator "#[bg=default,fg=#{@thm_overlay_2}]#[bg=#{@thm_overlay_2},fg=#{@thm_surface_0}]"
set -g @catppuccin_window_middle_separator "#[fg=#{@thm_overlay_2}]█"
set -g @catppuccin_window_right_separator "#[bg=default,fg=#{@thm_surface_0}]"
set -g @catppuccin_window_current_left_separator "#[bg=default,fg=#{@thm_mauve}]#[bg=#{@thm_mauve},fg=#{@thm_bg}]"
set -g @catppuccin_window_current_middle_separator "#[fg=#{@thm_mauve}]█"
set -g @catppuccin_window_current_right_separator "#[bg=default,fg=#{@thm_surface_1}]"

set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"

set -g status-bg default
set -g status-style bg=default

# Tabs on top
set-option -g status-position top

# Force the window name to be used instead of the hostname
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_current_text "#W"
set -g @catppuccin_window_text "#W"

# Ensure tmux is allowed to rename the window based on the process
setw -g automatic-rename on

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
